### ISSUE TITLE
_ in field name

### ISSUE THREAD

**Issue by ziporah** [logstash-plugins/logstash-input-journald#17]
Since ES 2.X and Kibana 3.X _names for fields don't seem to be wanted anymore and throw errors in the kibana view. Easy way around this is to mutate all _fields to non _fields and drop the _fields.
This can probably be done in the plugin. Is this something worth looking into, otherwise I will keep the mutate filter in place. This is a breaking change, since all fields will be indexed in another fieldname then the one expected !

**Comment by vaijab** [comment]
This plugin should be generic input plugin and not make any assumptions where ingested events should be pushed.

I use a mutate filter: https://github.com/UKHomeOffice/docker-logstash-kubernetes/blob/master/conf.d/20_output_journald_elasticsearch.conf

**Comment by stuart-warren** [comment]
I was at one point tinkering with removing the underscores:
stuart-warren/logstash-input-journald@393e52d93343261d33a4ab7282715a7f9e6ea98b

Though I can't remember if it was performant or even worked.

**Comment by untergeek** [comment]
I agree with the approach of mutating all _fields, but this is something that should be done in the mutate filter.  Inputs should generally be naive about inputs, and only put metadata fields into `@metadata` instead of mutating them.

One of the reasons that _ prepended fields are problematic is Elasticsearch, which adds metadata fields to each event which are prepended with _ as well.  Things get strange and/or broken if you send a prepended field named _id or _version.  This is not a reason to do the conversion in the input plugin, though.  A mutate filter is still the place where changes should happen.

I'm closing this as tabled for discussion in this input.  If you disagree, feel free to re-open and discuss your reasoning.

**Comment by DrMurx** [comment]
It would be awesome to mention potential issue with underscore fields and how to resolve it with mutate filters in the README.
